# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_files\add_prof.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddProf(object):
    def setupUi(self, AddProf):
        AddProf.setObjectName("AddProf")
        AddProf.resize(396, 191)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(AddProf)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(AddProf)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.le_prof = QtWidgets.QLineEdit(AddProf)
        self.le_prof.setObjectName("le_prof")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.le_prof)
        self.label_2 = QtWidgets.QLabel(AddProf)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.le_edu = QtWidgets.QLineEdit(AddProf)
        self.le_edu.setObjectName("le_edu")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.le_edu)
        self.verticalLayout.addLayout(self.formLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(AddProf)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(AddProf)
        QtCore.QMetaObject.connectSlotsByName(AddProf)

    def retranslateUi(self, AddProf):
        _translate = QtCore.QCoreApplication.translate
        AddProf.setWindowTitle(_translate("AddProf", "Добавить профессию"))
        self.label.setText(_translate("AddProf", "Профессия:"))
        self.label_2.setText(_translate("AddProf", "Образование:"))


class AddProf(QtWidgets.QWidget, Ui_AddProf):
    def __init__(self):
        super().__init__()
        self.setupUi(self)


def except_hook(cls, exception, traceback):
    sys.__excepthook__(cls, exception, traceback)


if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    ex = AddProf()
    ex.show()
    sys.excepthook = except_hook
    sys.exit(app.exec())
